/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pandroid_JNIInterface */

#ifndef _Included_com_pandroid_JNIInterface
#define _Included_com_pandroid_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pandroid_JNIInterface
 * Method:    setOtg2JNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pandroid_JNIInterface_setOtg2JNI
  (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_pandroid_JNIInterface_getOtgfromJNI
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
